### PR TITLE
Move attribute to Form_Element

### PR DESCRIPTION
**Pull request by thanegill**
- Removes redundant code
- Adds the ability to remove attributes
- Can now add attributes to Form
- getHtmlAttribute() returns all attributes including class

Conflicts:
    usr/local/www/classes/Form/Button.class.php
    usr/local/www/classes/Form/Select.class.php

Same as #32 just new source branch.

### CODE REVIEW

**Comment by thanegill** [comment]
@SjonHortensius Any more thoughts on this?

**Comment by SjonHortensius** [comment]
I've had various thoughts but I'll keep those to myself. Anyway; your PR is now merged

**Comment by thanegill** [comment]
These classes will continue to evolve as we progress though our conversion. I highly doubt anything this is this PR is final. Thanks for the changes and suggestions. I'm more than willing to hear your ideas that you have for these classes.

**Comment by SjonHortensius** [comment]
To be honest it felt like you spent time refactoring things (esp. codestyle related) for which I then spent time refactoring it the other way around. But the general idea was good and I'm happy it's done

**Pull request merged**
