### PR TITLE
Move attribute to Form_Element

### PR DESCRIPTION
**Pull request by thanegill**
- Removes redundant code
- Adds the ability to remove attributes
- Can now add attributes to Form
- getHtmlAttribute() returns all attributes including class

### CODE REVIEW

**Comment by psophis** [comment]
Updated with changes.

**Comment by thanegill** [comment]
Updated and fixed.

**Comment by SjonHortensius** [comment]
This change could be useful and cleans some things up nicely, but the current setup is more explicit and (hopefully) encourages developers to use explicit calls (eg. setAction vs `setAttribute('action')`). I'm also actually considering removing setAttribute and add explicit methods for setDisabled, and setToggle instead.

I realize Input::setAttribute already exists and weakens my argument; could you provide an example where you _need_ setAttribute and an explicit function wouldn't be better?

**Comment by thanegill** [comment]
While I agree that explicit calls would be better, setAction() is still there (Though now thinking about it, it might be better suited as a constructor argument). I liked the idea of moving setAttribute() to Form_Element because removes code redundancy. It doesn't need to be public though, it could just be a protected method that gets called by Form_Elements children. 

As of now there are no needs for calling setAttribute() outside of the object except for data-toggle and disabled which adding explicit methods for would be a good idea

**Comment by thanegill** [comment]
Created a new PR with a different source branch #37

**Pull request closed without merging**
