### PR TITLE
Updated for consistency with reboot.php

### PR DESCRIPTION
**Pull request by sbeaver-netgate**
Updated for consistency with reboot.php

### CODE REVIEW

**Comment by SjonHortensius** [comment]
This change is okay; but please update your fork first. You'll receive Sander's changes and should then apply yours.

Now you're submitting a new version of your file while it was also changed in the repo, meaning I would need to manually merge them

**Comment by sbeaver-netgate** [comment]
Just when I thought I was beginning to understand git :)

Time to go outside and enjoy the spring flowers.

Steve

> On Apr 19, 2015, at 11:21 AM, SjonHortensius notifications@github.com wrote:
> 
> This change is okay; but please update your fork first. You'll receive Sander's changes and should then apply yours.
> 
> Now you're submitting a new version of your file while it was also changed in the repo, meaning I would need to manually merge them
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/SjonHortensius/pfsense/pull/100#issuecomment-94287534.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/

**Comment by sbeaver-netgate** [comment]
git pull https://github.com/SjonHortensius/pfsense.git https://github.com/SjonHortensius/pfsense.git

Then from the GitHub GIU “Update branch from Bootstrap”

Made my edits to halt.php, committed and synced.

Sander’s changes were actually my changes that he merged last week, so I think we have ended up in the same place.

Steve

**Comment by SjonHortensius** [comment]
I have reverted this PR and cherry-picked the commits in bef0adce5.

**Comment by sbeaver-netgate** [comment]
Thank you.

Please let me know when you fork is ready to pull from again.

Steve

> On Apr 28, 2015, at 8:03 AM, SjonHortensius notifications@github.com wrote:
> 
> I have reverted this PR and cherry-picked the commits in bef0adc https://github.com/SjonHortensius/pfsense/commit/bef0adce590d253e4f763b7d40c2e3288252993a.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/SjonHortensius/pfsense/pull/100#issuecomment-97036247.

## Steve

Stephen Beaver | +1 (512) 646-4100;239 | sbeaver@netgate.com mailto:sbeaver@netgate.com | www.netgate.com http://www.netgate.com/

**Pull request merged**
