### PR TITLE
Interface > VLANs

### PR DESCRIPTION
**Pull request by thanegill**
TODO:
- [x] Hide id label on re-edit #10
- [x] Hide vlanif label #11
- [x] Add cancel button to edit #11

### CODE REVIEW

**Comment by thanegill** [comment]
This should be ready to be merged.

**Comment by thanegill** [comment]
I can remove them for this PR. I was adding brackets when I ran `clean.sh` Should I not be runing `clean.sh` before converting a page?

**Comment by thanegill** [comment]
Commit to add brackets has been removed.

**Comment by SjonHortensius** [comment]
Obviously you should run the clean.sh; but that doesn't add magic brackets as far as I know ;)

merged!

**Pull request merged**
